# Generated by Django 2.2.7 on 2019-11-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_system",
            field=models.BooleanField(default=False, help_text="システムユーザ", verbose_name="system status",),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, help_text="アクティブユーザ", verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, help_text="スタッフユーザ", verbose_name="staff status"),
        ),
    ]
