# Generated by Django 3.1 on 2021-11-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20191127_1543"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="password_reset_token"),
        ),
    ]
